---

language: python
services: docker

env:
  global:
    - ROLE_NAME: certbot
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-source-install.yml
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-source-install.yml
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME nkakouros.$ROLE_NAME
  - cd nkakouros.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
