---

- include_tasks: variables.yml

- include_tasks: install.yml

- include_tasks: hooks.yml
  when: certbot_hooks_enable | bool

- include_tasks: standalone.yml
  loop: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert_item
  when:
    - certbot_create_if_missing | bool
    - certbot_create_method == 'standalone'

- include_tasks: systemd.yml
  when:
    - certbot_auto_renew | bool
