---

- include_tasks: include-vars.yml

- include_tasks: install-with-package.yml
  when: not certbot_install_from_source | bool

- include_tasks: install-from-source.yml
  when: certbot_install_from_source | bool

- include_tasks: hooks.yml
  when: certbot_hooks_enable | bool

- include_tasks: standalone.yml
  loop: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert_item
  when:
    - certbot_create_if_missing | bool
    - certbot_create_method == 'standalone'

- include_tasks: systemd.yml
  when:
    - certbot_auto_renew
    - certbot_auto_renew_systemd

- include_tasks: renew-cron.yml
  when:
    - certbot_auto_renew
    - not certbot_auto_renew_systemd
