---

- name: Create pre and post hook folders
  file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: 0o755
  loop:
    - pre
    - post

- name: Create pre hook to stop services
  template:
    src: pre-hook.j2
    dest: /etc/letsencrypt/renewal-hooks/pre/hook
    mode: 0o750

- name: Create post hook to start services
  template:
    src: post-hook.j2
    dest: /etc/letsencrypt/renewal-hooks/post/hook
    mode: 0o750
