---

- name: Create pre and post hook folders
  file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: 0o755
    owner: root
    group: root
  loop:
    - pre
    - post

- name: Create pre hook to stop services
  template:
    src: pre-hook.j2
    dest: /etc/letsencrypt/renewal-hooks/pre/hook
    owner: root
    group: root
    mode: 0o750
  when: certbot_create_standalone_stop_services | length > 0

- name: Create post hook to start services
  template:
    src: post-hook.j2
    dest: /etc/letsencrypt/renewal-hooks/post/hook
    owner: root
    group: root
    mode: 00750
